apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./coit-backend1-deployment.yaml
  - ./coit-backend1-service.yaml
images:
  - name: kollidatta/backend1
    newTag: 4.0.0
configMapGenerator:
  - name: coit-backend1-config
    envs:
      - application.properties
secretGenerator:
  - name: coit-backend1-secrets
    envs:
      - applicationsecrets.properties
namePrefix: customer1-
nameSuffix: -development
commonLabels:
  customer: customer1
  environment: development
  myapp: coit-backend1
  app: coitbackend1
labels:
  - pairs:
      location: us-west
