apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

images:
  - name: coitlearning/coit-backend1
    newTag: 1.0.0
    newName: coitlearning/coit-backend1

commonLabels:
  environment: production 

nameSuffix: -production
replicas:
  - name: coit-backend1
    count: 10

namespace: production
